# Generated by Django 6.0.3 on 2026-03-27 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('anio_fabricacion', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Aeronave',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='ClaseServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ECONOMICA', 'Económica'), ('ECONOMICA_PREMIUM', 'Económica Premium'), ('EJECUTIVA', 'Ejecutiva (Business)'), ('PRIMERA', 'Primera Clase')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ClaseServicio',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='ModeloAeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('capacidad_maxima', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ModeloAeronave',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Países',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='PeriodoItinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('MAR_JUL', 'Marzo – Julio'), ('JUL_NOV', 'Julio – Noviembre'), ('NOV_MAR', 'Noviembre – Marzo')], max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'PeriodoItinerario',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('es_bodega', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TipoEquipaje',
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('letra', models.CharField(max_length=2)),
                ('junto_ventana', models.BooleanField(default=False)),
                ('junto_pasillo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento')], default='OPERATIVO', max_length=20)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='app.aeronave')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.claseservicio')),
            ],
            options={
                'db_table': 'Asiento',
                'unique_together': {('aeronave', 'fila', 'letra')},
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aeropuertos', to='app.ciudad')),
            ],
            options={
                'db_table': 'Aeropuerto',
            },
        ),
        migrations.AddField(
            model_name='aeronave',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aeronaves', to='app.modeloaeronave'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='app.pais'),
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_pasaporte', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pais')),
            ],
            options={
                'db_table': 'Pasajero',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('dias_operacion', models.CharField(max_length=50)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llegadas', to='app.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='app.aeropuerto')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itinerarios', to='app.periodoitinerario')),
            ],
            options={
                'db_table': 'Itinerario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('IDA', 'Solo ida'), ('IDA_VUELTA', 'Ida y vuelta'), ('MULTIDESTINO', 'Multidestino')], max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='app.cliente')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('seleccion_asiento_incluida', models.BooleanField(default=False)),
                ('cargo_seleccion_asiento', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.claseservicio')),
            ],
            options={
                'db_table': 'Tarifa',
            },
        ),
        migrations.CreateModel(
            name='SegmentoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pasajero')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='app.reserva')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tarifa')),
            ],
            options={
                'db_table': 'SegmentoReserva',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EquipajeReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cargo_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pasajero')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipajes', to='app.segmentoreserva')),
                ('tipo_equipaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipoequipaje')),
            ],
            options={
                'db_table': 'EquipajeReserva',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(editable=False, max_length=15, unique=True)),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('hora_salida_real', models.TimeField(blank=True, null=True)),
                ('hora_llegada_real', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EMBARCANDO', 'Embarcando'), ('EN_VUELO', 'En vuelo'), ('ATERRIZADO', 'Aterrizado'), ('CANCELADO', 'Cancelado'), ('DEMORADO', 'Demorado')], default='PROGRAMADO', max_length=20)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='app.aeronave')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='app.itinerario')),
            ],
            options={
                'db_table': 'Vuelo',
                'unique_together': {('numero_vuelo', 'fecha_salida')},
            },
        ),
        migrations.AddField(
            model_name='tarifa',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='app.vuelo'),
        ),
        migrations.AddField(
            model_name='segmentoreserva',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vuelo'),
        ),
        migrations.CreateModel(
            name='ConfiguracionClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asientos', models.PositiveIntegerField()),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='app.aeronave')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.claseservicio')),
            ],
            options={
                'db_table': 'ConfiguracionClase',
                'unique_together': {('aeronave', 'clase')},
            },
        ),
        migrations.CreateModel(
            name='AsientoReservado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.asiento')),
                ('segmento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asiento_reservado', to='app.segmentoreserva')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('segmento', 'asiento'), name='unique_asiento_por_segmento')],
            },
        ),
        migrations.CreateModel(
            name='PoliticaEquipaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima', models.PositiveIntegerField()),
                ('peso_maximo_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_equipaje', to='app.tarifa')),
                ('tipo_equipaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipoequipaje')),
            ],
            options={
                'db_table': 'PoliticaEquipaje',
                'unique_together': {('tarifa', 'tipo_equipaje')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together={('vuelo', 'clase')},
        ),
        migrations.AlterUniqueTogether(
            name='segmentoreserva',
            unique_together={('reserva', 'vuelo', 'pasajero')},
        ),
    ]
