# Generated by Django 6.0.3 on 2026-03-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asientoreservado',
            table='AsientoReservado',
        ),
    ]
